apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - ../../apps/overlays/dev
  - ../../infrastructure
patches:
  - path: flux-patches.yaml
    target:
      kind: ServiceAccount
      name: image-reflector-controller
      namespace: flux-system