apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: underwater
  namespace: flux-system
spec:
  image: 495905914919.dkr.ecr.us-east-1.amazonaws.com/underwater
  interval: 1m
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: auth-service
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: underwater
  filterTags:
    pattern: "^dev-([0-9]+)$"
    extract: "$1"
  policy:
    numerical:
      order: asc