apiVersion: v1
kind: Service
metadata:
  name: ecr-app-api-service
  namespace: api-service
spec:
  selector:
    app: api-service
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  type: ClusterIP